import type { JarvisKnowledgeChunk, JarvisKnowledgeDocument } from './types.ts';

const DOCUMENTS = 'jarvis_knowledge_documents'; const CHUNKS = 'jarvis_knowledge_chunks';
export interface JarvisKnowledgeRepository { listDocuments(organizationId: string): Promise<JarvisKnowledgeDocument[]>; listChunks(organizationId: string): Promise<JarvisKnowledgeChunk[]>; }
function database(table: string) { const base = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '').replace(/\/$/, ''); const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY || ''; if (!base || !key) throw new Error('JARVIS knowledge storage is not configured.'); return { url: `${base}/rest/v1/${table}`, headers: { apikey: key, Authorization: `Bearer ${key}` } }; }
function document(row: Record<string, unknown>): JarvisKnowledgeDocument { return { id: String(row.id), organizationId: String(row.organization_id), title: String(row.title), sourceType: row.source_type as JarvisKnowledgeDocument['sourceType'], authority: row.authority as JarvisKnowledgeDocument['authority'], domain: String(row.domain), department: row.department ? String(row.department) : undefined, version: String(row.version), status: row.status as JarvisKnowledgeDocument['status'], owner: row.owner ? String(row.owner) : undefined, sourceUrl: row.source_url ? String(row.source_url) : undefined, fileReference: row.file_reference ? String(row.file_reference) : undefined, supersedesDocumentId: row.supersedes_document_id ? String(row.supersedes_document_id) : undefined, effectiveFrom: row.effective_from ? String(row.effective_from) : undefined, effectiveUntil: row.effective_until ? String(row.effective_until) : null, visibilityRoles: Array.isArray(row.visibility_roles) ? row.visibility_roles.map(String) : ['director'], checksum: row.checksum ? String(row.checksum) : undefined, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function chunk(row: Record<string, unknown>): JarvisKnowledgeChunk { return { id: String(row.id), documentId: String(row.document_id), organizationId: String(row.organization_id), heading: row.heading ? String(row.heading) : undefined, sectionPath: row.section_path ? String(row.section_path) : undefined, page: row.page == null ? undefined : Number(row.page), text: String(row.text), keywords: Array.isArray(row.keywords) ? row.keywords.map(String) : [], claimKind: row.claim_kind as JarvisKnowledgeChunk['claimKind'], chunkIndex: Number(row.chunk_index), createdAt: String(row.created_at) }; }
export class SupabaseJarvisKnowledgeRepository implements JarvisKnowledgeRepository { async listDocuments(organizationId: string) { const db = database(DOCUMENTS); const response = await fetch(`${db.url}?organization_id=eq.${encodeURIComponent(organizationId)}&select=*`, { headers: db.headers }); if (!response.ok) throw new Error(`Unable to retrieve JARVIS knowledge documents (${response.status}).`); return (await response.json() as Record<string, unknown>[]).map(document); } async listChunks(organizationId: string) { const db = database(CHUNKS); const response = await fetch(`${db.url}?organization_id=eq.${encodeURIComponent(organizationId)}&select=*`, { headers: db.headers }); if (!response.ok) throw new Error(`Unable to retrieve JARVIS knowledge chunks (${response.status}).`); return (await response.json() as Record<string, unknown>[]).map(chunk); } }
export class InMemoryJarvisKnowledgeRepository implements JarvisKnowledgeRepository {
  documents: JarvisKnowledgeDocument[];
  chunks: JarvisKnowledgeChunk[];
  constructor(documents: JarvisKnowledgeDocument[] = [], chunks: JarvisKnowledgeChunk[] = []) { this.documents = documents; this.chunks = chunks; }
  async listDocuments(organizationId: string) { return this.documents.filter(item => item.organizationId === organizationId); }
  async listChunks(organizationId: string) { return this.chunks.filter(item => item.organizationId === organizationId); }
}
