import assert from 'node:assert/strict'; import test from 'node:test';
import { InMemoryJarvisKnowledgeRepository } from './repository.ts'; import { JarvisKnowledgeService } from './service.ts'; import { chunkKnowledge } from './ingestion.ts';
import { needsKnowledgeRetrieval } from './policy.ts';
const now = '2026-08-28T00:00:00.000Z';
function doc(overrides: Record<string, unknown> = {}) { return { id: 'po-v3', organizationId: 'varindo', title: 'Purchase Order SOP', sourceType: 'SOP', authority: 'OFFICIAL', domain: 'purchasing', version: 'v3', status: 'ACTIVE', effectiveFrom: '2026-01-01', visibilityRoles: ['director'], createdAt: now, updatedAt: now, ...overrides } as any; }
test('ranks current official policy ahead of an older reference', async () => { const current = doc(); const old = doc({ id: 'po-v2', version: 'v2', authority: 'REFERENCE', status: 'SUPERSEDED', effectiveFrom: '2025-01-01' }); const repo = new InMemoryJarvisKnowledgeRepository([current, old], [...chunkKnowledge(current, '4. Approval\nDirector approval is required.'), ...chunkKnowledge(old, '4. Approval\nOld approval guidance.')]); const found = await new JarvisKnowledgeService(repo).search({ organizationId: 'varindo', role: 'director', query: 'purchase order approval procedure' }); assert.equal(found.results[0].documentId, 'po-v3'); });
test('filters unauthorized and inactive knowledge before ranking', async () => { const secure = doc({ visibilityRoles: ['admin'] }); const repo = new InMemoryJarvisKnowledgeRepository([secure], chunkKnowledge(secure, 'Internal purchasing procedure.')); const found = await new JarvisKnowledgeService(repo).search({ organizationId: 'varindo', role: 'director', query: 'purchasing procedure' }); assert.equal(found.results.length, 0); });
test('preserves exact product codes and rejects secret-like ingestion', () => { const product = doc({ id: 'product', sourceType: 'PRODUCT_DOCUMENTATION', domain: 'products' }); assert.match(chunkKnowledge(product, 'DWE9004L\nSpecification table')[0].text, /DWE9004L/); assert.throws(() => chunkKnowledge(product, 'API_KEY=do-not-store')); });
test('does not use governed knowledge for a current-stock request', () => { assert.equal(needsKnowledgeRetrieval('What is the current stock for DWE9004L?'), false); });
