// ─── Handoff reasons & team routing ──────────────────────────────────────────
// VIA Customer Operations Phase 8, brief sections 3, 8-11: deterministic
// reasons only — never a handoff created "because Jarvis feels uncertain."
// TEAM_FOR_REASON is the whole assignment engine's routing table; unmapped
// reasons fall back to DEFAULT_CUSTOMER_SERVICE_QUEUE so NEEDS_HUMAN can
// never go unassigned indefinitely (section 11).

export type HandoffReason =
  | 'CUSTOMER_REQUESTED_HUMAN' | 'AMBIGUOUS_CUSTOMER' | 'AMBIGUOUS_PRODUCT' | 'PRICE_NOT_FOUND'
  | 'PRICE_CONFLICT' | 'DISCOUNT_REQUEST' | 'SPECIAL_PRICING' | 'LARGE_PROJECT_QUOTE'
  | 'STOCK_RESPONSE_AMBIGUOUS' | 'VENDOR_TIMEOUT' | 'ORDER_MODIFICATION' | 'ORDER_CANCELLATION'
  | 'PAYMENT_REVIEW' | 'PAYMENT_PROOF_RECEIVED' | 'DELIVERY_STATUS_UNAVAILABLE' | 'NEW_ADDRESS_REVIEW'
  | 'CUSTOMER_DUPLICATE_REVIEW' | 'ZOHO_WRITE_FAILURE' | 'IDENTITY_VERIFICATION_REQUIRED'
  | 'SECURITY_SENSITIVE_REQUEST' | 'COMPLAINT' | 'AI_UNAVAILABLE' | 'OTHER_EXCEPTION';

export type ServiceTeam = 'CUSTOMER_SERVICE' | 'SALES' | 'FINANCE' | 'OPERATIONS' | 'MANAGEMENT';

export const DEFAULT_CUSTOMER_SERVICE_QUEUE: ServiceTeam = 'CUSTOMER_SERVICE';

/** Brief section 10's example routing, made exhaustive over the full reason enum. Never guessed per-conversation — one fixed table. */
const TEAM_FOR_REASON: Record<HandoffReason, ServiceTeam> = {
  CUSTOMER_REQUESTED_HUMAN: 'CUSTOMER_SERVICE',
  AMBIGUOUS_CUSTOMER: 'CUSTOMER_SERVICE',
  AMBIGUOUS_PRODUCT: 'CUSTOMER_SERVICE',
  PRICE_NOT_FOUND: 'SALES',
  PRICE_CONFLICT: 'SALES',
  DISCOUNT_REQUEST: 'SALES',
  SPECIAL_PRICING: 'SALES',
  LARGE_PROJECT_QUOTE: 'SALES',
  STOCK_RESPONSE_AMBIGUOUS: 'OPERATIONS',
  VENDOR_TIMEOUT: 'OPERATIONS',
  ORDER_MODIFICATION: 'CUSTOMER_SERVICE',
  ORDER_CANCELLATION: 'CUSTOMER_SERVICE',
  PAYMENT_REVIEW: 'FINANCE',
  PAYMENT_PROOF_RECEIVED: 'FINANCE',
  DELIVERY_STATUS_UNAVAILABLE: 'OPERATIONS',
  NEW_ADDRESS_REVIEW: 'CUSTOMER_SERVICE',
  CUSTOMER_DUPLICATE_REVIEW: 'CUSTOMER_SERVICE',
  ZOHO_WRITE_FAILURE: 'OPERATIONS',
  IDENTITY_VERIFICATION_REQUIRED: 'CUSTOMER_SERVICE',
  SECURITY_SENSITIVE_REQUEST: 'CUSTOMER_SERVICE',
  COMPLAINT: 'CUSTOMER_SERVICE',
  AI_UNAVAILABLE: 'CUSTOMER_SERVICE',
  OTHER_EXCEPTION: 'CUSTOMER_SERVICE',
};

export function teamForReason(reason: HandoffReason): ServiceTeam {
  return TEAM_FOR_REASON[reason] ?? DEFAULT_CUSTOMER_SERVICE_QUEUE;
}
