"use client";

import { useState, useEffect, useMemo, useCallback } from "react";
import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

type Period = "this_month" | "prev_month" | "this_year" | "prev_year";
type ReportType = "item" | "brand" | "location" | "customer" | "salesperson";
type SortDir = "asc" | "desc";

interface DashboardSummary {
  monthly_sales: { from: string; to: string; revenueBeforePpn: number; invoiceCount: number };
  gross_profit: { grossProfit: number; cogs: number; gpMargin: number };
  receivables: { totalReceivables: number; invoiceCount: number; overdueReceivables: number };
  inventory_summary: {
    stockValue: number; stockQty: number; itemCount: number;
    by_brand: Array<{ brand: string; stockValue: number; stockQty: number; itemCount: number }>;
  };
}

interface ReportRow {
  name: string;
  sku?: string;
  unit?: string;
  quantity?: number;
  amount: number;
  avg_price?: number;
  count?: number;
  invoice_count?: number;
  customer_count?: number;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const mono = { fontFamily: "JetBrains Mono, monospace" };
const formatRp = (n: number) => "Rp " + Math.round(n).toLocaleString("id-ID");
const formatQty = (n: number) => Number(n).toLocaleString("id-ID");
const formatPct = (n: number) => ((n || 0) * 100).toFixed(1) + "%";

const PERIODS: { key: Period; label: string }[] = [
  { key: "this_month", label: "This Month" },
  { key: "prev_month", label: "Previous Month" },
  { key: "this_year", label: "This Year" },
  { key: "prev_year", label: "Previous Year" },
];

const REPORT_TYPES: {
  key: ReportType;
  label: string;
  desc: string;
  icon: string;
}[] = [
  {
    key: "item",
    label: "Sales by Item",
    desc: "Revenue breakdown by item",
    icon: "▣",
  },
  {
    key: "brand",
    label: "Sales by Brand",
    desc: "Revenue breakdown by brand",
    icon: "◈",
  },
  {
    key: "location",
    label: "Sales by Location",
    desc: "Revenue by warehouse/location",
    icon: "⊙",
  },
  {
    key: "customer",
    label: "Sales by Customer",
    desc: "Revenue breakdown by customer",
    icon: "◎",
  },
  {
    key: "salesperson",
    label: "Sales by Salesperson",
    desc: "Revenue generated by salesperson",
    icon: "◇",
  },
];

function MetricCard({ title, value, subtitle, tone = "default" }: { title: string; value: string; subtitle: string; tone?: "default" | "accent" | "warning" | "good" }) {
  const color = tone === "accent" ? "var(--accent)" : tone === "warning" ? "var(--warning)" : tone === "good" ? "var(--success)" : "var(--text)";
  return (
    <div style={{ background: "var(--panel)", border: "1px solid var(--border)", borderRadius: 12, padding: 18, minHeight: 120 }}>
      <div style={{ color: "var(--muted)", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 12 }}>
        {title}
      </div>
      <div style={{ color, fontSize: 24, fontWeight: 700, fontFamily: "JetBrains Mono, monospace" }}>
        {value}
      </div>
      <div style={{ color: "var(--muted)", fontSize: 12, marginTop: 8, lineHeight: 1.4 }}>
        {subtitle}
      </div>
    </div>
  );
}

function MonthlySummaryCards() {
  const [data, setData] = useState<DashboardSummary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch("/api/dashboard", { cache: "no-store" });
        const json = await res.json();
        if (json.success !== false) setData(json);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-5">
      <MetricCard
        title="Monthly Sales Before PPN"
        value={loading && !data ? "Loading…" : formatRp(data?.monthly_sales.revenueBeforePpn || 0)}
        subtitle={`${data?.monthly_sales.invoiceCount || 0} invoices this month`}
        tone="accent"
      />
      <MetricCard
        title="Gross Profit This Month"
        value={loading && !data ? "Loading…" : formatRp(data?.gross_profit.grossProfit || 0)}
        subtitle={`COGS ${formatRp(data?.gross_profit.cogs || 0)} · GP margin ${formatPct(data?.gross_profit.gpMargin || 0)}`}
        tone="good"
      />
      <MetricCard
        title="Total Receivables"
        value={loading && !data ? "Loading…" : formatRp(data?.receivables.totalReceivables || 0)}
        subtitle={`${data?.receivables.invoiceCount || 0} unpaid invoices · Overdue ${formatRp(data?.receivables.overdueReceivables || 0)}`}
        tone="warning"
      />
      <div style={{ background: "var(--panel)", border: "1px solid var(--border)", borderRadius: 12, padding: 18, minHeight: 120 }}>
        <div style={{ color: "var(--muted)", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 12 }}>
          Inventory Summary Value
        </div>
        <div style={{ color: "var(--text)", fontSize: 24, fontWeight: 700, fontFamily: "JetBrains Mono, monospace" }}>
          {loading && !data ? "Loading…" : formatRp(data?.inventory_summary.stockValue || 0)}
        </div>
        <div style={{ color: "var(--muted)", fontSize: 12, marginTop: 6, marginBottom: 10 }}>
          {formatQty(data?.inventory_summary.stockQty || 0)} sheets/items · {data?.inventory_summary.itemCount || 0} active items
        </div>
        {data?.inventory_summary.by_brand?.length ? (
          <div style={{ borderTop: "1px solid var(--border)", paddingTop: 10, display: "flex", flexDirection: "column", gap: 5 }}>
            {data.inventory_summary.by_brand.map(b => (
              <div key={b.brand} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 }}>
                <span style={{ color: "var(--muted)", fontSize: 11, fontFamily: "JetBrains Mono, monospace", minWidth: 70 }}>{b.brand}</span>
                <div style={{ flex: 1, height: 3, borderRadius: 2, background: "var(--border)", overflow: "hidden" }}>
                  <div style={{
                    height: "100%",
                    borderRadius: 2,
                    background: "var(--accent)",
                    width: `${Math.round((b.stockValue / (data.inventory_summary.stockValue || 1)) * 100)}%`,
                  }} />
                </div>
                <span style={{ color: "var(--text)", fontSize: 11, fontFamily: "JetBrains Mono, monospace", textAlign: "right", minWidth: 90 }}>
                  {formatRp(b.stockValue)}
                </span>
              </div>
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
}

function SortIcon({ active, dir }: { active: boolean; dir: SortDir }) {
  if (!active)
    return (
      <span style={{ color: "var(--text-4)", marginLeft: 4, fontSize: 9 }}>
        ↕
      </span>
    );
  return (
    <span style={{ color: "var(--accent)", marginLeft: 4, fontSize: 9 }}>
      {dir === "asc" ? "↑" : "↓"}
    </span>
  );
}

function SkeletonRows({ cols }: { cols: number }) {
  return (
    <>
      {[...Array(8)].map((_, i) => (
        <tr key={i} className="animate-pulse">
          {[...Array(cols)].map((_, j) => (
            <td key={j} style={{ padding: "10px 12px" }}>
              <div
                style={{
                  height: 12,
                  background: "var(--surface-3)",
                  borderRadius: 4,
                  width: j === 0 ? "70%" : "50%",
                }}
              />
            </td>
          ))}
        </tr>
      ))}
    </>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function SalesReportsPage() {
  const [period, setPeriod] = useState<Period>("this_month");
  const [reportType, setReportType] = useState<ReportType>("item");
  const [rows, setRows] = useState<ReportRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [dateRange, setDateRange] = useState("");
  const [sortKey, setSortKey] = useState<
    "amount" | "quantity" | "avg_price" | "name"
  >("amount");
  const [sortDir, setSortDir] = useState<SortDir>("desc");
  const [search, setSearch] = useState("");

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await fetch(`/api/reports?type=${reportType}&period=${period}`);
      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      setRows(data.rows as ReportRow[]);
      setDateRange(data.from && data.to ? `${data.from} – ${data.to}` : "");
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, [reportType, period]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  function handleSort(key: typeof sortKey) {
    if (sortKey === key) setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    else {
      setSortKey(key);
      setSortDir("desc");
    }
  }

  const filtered = useMemo(() => {
    let r = rows;
    if (search.trim()) {
      const q = search.toLowerCase();
      r = r.filter(
        (row) =>
          row.name.toLowerCase().includes(q) ||
          (row.sku || "").toLowerCase().includes(q),
      );
    }
    return [...r].sort((a, b) => {
      const av = sortKey === "name" ? a.name : a[sortKey] || 0;
      const bv = sortKey === "name" ? b.name : b[sortKey] || 0;
      if (typeof av === "string")
        return sortDir === "asc"
          ? av.localeCompare(bv as string)
          : (bv as string).localeCompare(av);
      return sortDir === "asc"
        ? (av as number) - (bv as number)
        : (bv as number) - (av as number);
    });
  }, [rows, search, sortKey, sortDir]);

  const totals = useMemo(() => {
    const amount = rows.reduce((s, r) => s + r.amount, 0);
    // Qty is only a meaningful single number when every row shares the same unit
    // (sheets). Edge banding/newedge items are sold by the meter, not the sheet —
    // mixing them into one "sht" total would misrepresent both. Rows without a
    // unit (brand/location/customer/salesperson reports don't carry one) are left
    // untouched, since this filter only applies where per-row unit is known.
    const quantity = rows.reduce((s, r) => s + (!r.unit || r.unit === "sht" ? (r.quantity || 0) : 0), 0);
    const edgeQuantity = rows.reduce((s, r) => s + (r.unit === "m" ? (r.quantity || 0) : 0), 0);
    return { amount, quantity, edgeQuantity };
  }, [rows]);

  // Brand color map
  const brandColors: Record<string, string> = {
    Lamitak: "#2563eb",
    EDL: "#16a34a",
    AICA: "#d97706",
    TACO: "#dc2626",
    CARTA: "#7c3aed",
  };

  const thStyle: React.CSSProperties = {
    padding: "9px 12px",
    textAlign: "left",
    cursor: "pointer",
    userSelect: "none",
    color: "var(--text-3)",
    fontWeight: 500,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    background: "var(--surface-2)",
    borderBottom: "1px solid var(--border)",
    whiteSpace: "nowrap",
  };

  const currentType = REPORT_TYPES.find((t) => t.key === reportType)!;

  return (
    <div
      style={{
        background: "var(--bg)",
        minHeight: "100%",
        padding: "24px 24px 80px",
      }}
    >
      <div style={{ maxWidth: 1400, margin: "0 auto" }}>
        {/* Page header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-[var(--text)] font-semibold text-2xl tracking-tight">
              Sales Reports
            </h1>
            <p className="text-[var(--text-3)] text-sm mt-0.5">
              {dateRange ? `${dateRange}` : "Loading…"}
            </p>
          </div>
          <button
            onClick={fetchData}
            disabled={loading}
            className="px-3 py-1.5 text-xs bg-[var(--surface-2)] hover:bg-[var(--surface-3)] text-[var(--text-3)] rounded-lg border border-[var(--border)] transition-colors disabled:opacity-50"
            style={mono}
          >
            {loading ? "…" : "↻"}
          </button>
        </div>

        <MonthlySummaryCards />

        {/* Period tabs */}
        <div className="flex items-center gap-2 mb-5">
          {PERIODS.map((p) => (
            <button
              key={p.key}
              onClick={() => setPeriod(p.key)}
              className={`px-4 py-2 text-xs font-medium rounded-lg border transition-all ${
                period === p.key
                  ? "bg-[var(--accent)] text-white border-[var(--accent)]"
                  : "bg-[var(--surface-2)] text-[var(--text-3)] border-[var(--border)] hover:bg-[var(--surface-3)]"
              }`}
            >
              {p.label}
            </button>
          ))}
        </div>

        {/* Report type cards */}
        <div className="grid grid-cols-5 gap-3 mb-5">
          {REPORT_TYPES.map((t) => (
            <button
              key={t.key}
              onClick={() => setReportType(t.key)}
              className={`via-card p-4 text-left transition-all border-2 ${
                reportType === t.key
                  ? "border-[var(--accent)] bg-[var(--accent-light)]"
                  : "border-transparent hover:border-[var(--border)]"
              }`}
            >
              <div className="flex items-center gap-2 mb-1">
                <span
                  style={{
                    fontSize: 14,
                    color:
                      reportType === t.key ? "var(--accent)" : "var(--text-3)",
                  }}
                >
                  {t.icon}
                </span>
                <span
                  className={`text-xs font-semibold ${reportType === t.key ? "text-[var(--accent)]" : "text-[var(--text)]"}`}
                >
                  {t.label}
                </span>
              </div>
              <p className="text-[var(--text-4)] text-xs">{t.desc}</p>
            </button>
          ))}
        </div>

        {/* Summary strip */}
        {!loading && rows.length > 0 && (
          <div className="flex items-center gap-6 mb-4 px-4 py-3 bg-[var(--surface-2)] rounded-lg border border-[var(--border)]">
            {reportType !== "salesperson" && (
              <>
                <div>
                  <div className="text-[var(--text-4)] text-xs uppercase tracking-wider mb-0.5">
                    Total Qty HPL
                  </div>
                  <div
                    className="text-[var(--text)] font-bold text-sm"
                    style={mono}
                  >
                    {formatQty(totals.quantity)} sht
                  </div>
                </div>
                {reportType === "item" && (
                  <>
                    <div className="w-px h-8 bg-[var(--border)]" />
                    <div>
                      <div className="text-[var(--text-4)] text-xs uppercase tracking-wider mb-0.5">
                        Total Qty Edge Band
                      </div>
                      <div
                        className="text-[var(--text)] font-bold text-sm"
                        style={mono}
                      >
                        {formatQty(totals.edgeQuantity)} m
                      </div>
                    </div>
                  </>
                )}
              </>
            )}
            <div>
              <div className="text-[var(--text-4)] text-xs uppercase tracking-wider mb-0.5">
                Total Revenue
              </div>
              <div
                className="text-[var(--text)] font-bold text-sm"
                style={mono}
              >
                {formatRp(totals.amount)}
              </div>
            </div>
            <div className="w-px h-8 bg-[var(--border)]" />
            <div>
              <div className="text-[var(--text-4)] text-xs uppercase tracking-wider mb-0.5">
                {currentType.label}
              </div>
              <div
                className="text-[var(--text)] font-bold text-sm"
                style={mono}
              >
                {rows.length} rows
              </div>
            </div>
            <div className="ml-auto">
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search…"
                className="via-input text-xs py-1.5 px-3 w-48"
              />
            </div>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="p-4 mb-4 bg-[var(--danger-bg)] border border-[var(--danger-border)] rounded-lg text-[var(--danger)] text-sm">
            {error}
          </div>
        )}

        {/* Table */}
        <div className="via-card overflow-hidden">
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                <th style={{ ...thStyle, width: 40, textAlign: "center" }}>#</th>

                {/* Name column */}
                <th style={thStyle} onClick={() => handleSort("name")}>
                  {reportType === "item"
                    ? "Item"
                    : reportType === "brand"
                      ? "Brand"
                      : reportType === "location"
                        ? "Location"
                        : reportType === "salesperson"
                          ? "Salesperson"
                          : "Customer"}
                  <SortIcon active={sortKey === "name"} dir={sortDir} />
                </th>

                {/* SKU for item report */}
                {reportType === "item" && (
                  <th style={{ ...thStyle, width: 140 }}>SKU</th>
                )}

                {reportType === "salesperson" ? (
                  <>
                    <th
                      style={{ ...thStyle, textAlign: "right", width: 160 }}
                      onClick={() => handleSort("amount")}
                    >
                      Revenue{" "}
                      <SortIcon active={sortKey === "amount"} dir={sortDir} />
                    </th>
                    <th style={{ ...thStyle, textAlign: "right", width: 95 }}>
                      Invoices
                    </th>
                    <th style={{ ...thStyle, textAlign: "right", width: 100 }}>
                      Customers
                    </th>
                    <th style={{ ...thStyle, width: 120 }}>Share</th>
                  </>
                ) : (
                  <>
                    <th
                      style={{ ...thStyle, textAlign: "right", width: 120 }}
                      onClick={() => handleSort("quantity")}
                    >
                      Qty Sold{" "}
                      <SortIcon active={sortKey === "quantity"} dir={sortDir} />
                    </th>
                    <th
                      style={{ ...thStyle, textAlign: "right", width: 150 }}
                      onClick={() => handleSort("avg_price")}
                    >
                      Avg Price{" "}
                      <SortIcon
                        active={sortKey === "avg_price"}
                        dir={sortDir}
                      />
                    </th>
                    <th
                      style={{ ...thStyle, textAlign: "right", width: 160 }}
                      onClick={() => handleSort("amount")}
                    >
                      Revenue{" "}
                      <SortIcon active={sortKey === "amount"} dir={sortDir} />
                    </th>
                    <th style={{ ...thStyle, width: 120 }}>Share</th>
                  </>
                )}
              </tr>
            </thead>
            <tbody>
              {loading && (
                <SkeletonRows cols={reportType === "item" ? 7 : 6} />
              )}
              {!loading && filtered.length === 0 && (
                <tr>
                  <td
                    colSpan={7}
                    style={{
                      padding: "40px",
                      textAlign: "center",
                      color: "var(--text-4)",
                      fontSize: 13,
                    }}
                  >
                    No data for this period.
                  </td>
                </tr>
              )}
              {!loading &&
                filtered.map((row, i) => {
                  const pct =
                    totals.amount > 0 ? (row.amount / totals.amount) * 100 : 0;
                  const brandColor =
                    reportType === "brand"
                      ? brandColors[row.name] || "var(--accent)"
                      : "var(--accent)";
                  const brand = row.sku
                    ? row.sku.split("-")[0].toUpperCase()
                    : "";
                  const brandLookup: Record<string, string> = {
                    LAM: "Lamitak",
                    EDL: "EDL",
                    EAS: "EDL",
                    AICA: "AICA",
                    TACO: "TACO",
                    TAC: "TACO",
                    CARTA: "CARTA",
                  };
                  const itemColor =
                    brandColors[brandLookup[brand] || ""] || "var(--accent)";

                  return (
                    <React.Fragment key={row.name}>
                      <tr
                        style={{
                          borderBottom: "1px solid var(--border-muted)",
                        }}
                        className="hover:bg-[var(--surface-2)] transition-colors"
                      >
                        <td
                          style={{
                            padding: "9px 12px",
                            textAlign: "center",
                            color: "var(--text-4)",
                            fontSize: 11,
                            ...mono,
                          }}
                        >
                          {i + 1}
                        </td>
                        <td style={{ padding: "9px 12px", maxWidth: 320 }}>
                          <div
                            style={{
                              color: "var(--text)",
                              fontSize: 12,
                              fontWeight: 500,
                              overflow: "hidden",
                              textOverflow: "ellipsis",
                              whiteSpace: "nowrap",
                            }}
                            title={row.name}
                          >
                            {reportType === "brand" && (
                              <span
                                style={{
                                  display: "inline-block",
                                  width: 8,
                                  height: 8,
                                  borderRadius: "50%",
                                  background: brandColor,
                                  marginRight: 6,
                                  verticalAlign: "middle",
                                }}
                              />
                            )}
                            {row.name}
                          </div>
                        </td>
                        {reportType === "item" && (
                          <td style={{ padding: "9px 12px" }}>
                            {row.sku && (
                              <span
                                style={{
                                  ...mono,
                                  fontSize: 10,
                                  color: itemColor,
                                  background: "var(--surface-3)",
                                  padding: "2px 6px",
                                  borderRadius: 4,
                                }}
                              >
                                {row.sku}
                              </span>
                            )}
                          </td>
                        )}
                        {reportType === "salesperson" ? (
                          <>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text)",
                                fontSize: 12,
                                fontWeight: 600,
                              }}
                            >
                              {formatRp(row.amount)}
                            </td>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text-3)",
                                fontSize: 12,
                              }}
                            >
                              {row.invoice_count || 0}
                            </td>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text-3)",
                                fontSize: 12,
                              }}
                            >
                              {row.customer_count || 0}
                            </td>
                            <td style={{ padding: "9px 12px" }}>
                              <div
                                style={{
                                  display: "flex",
                                  alignItems: "center",
                                  gap: 6,
                                }}
                              >
                                <div
                                  style={{
                                    flex: 1,
                                    height: 4,
                                    background: "var(--surface-3)",
                                    borderRadius: 2,
                                    overflow: "hidden",
                                  }}
                                >
                                  <div
                                    style={{
                                      width: `${Math.min(pct, 100)}%`,
                                      height: "100%",
                                      background: "var(--accent)",
                                      borderRadius: 2,
                                      transition: "width 0.3s ease",
                                    }}
                                  />
                                </div>
                                <span
                                  style={{
                                    ...mono,
                                    fontSize: 10,
                                    color: "var(--text-4)",
                                    minWidth: 32,
                                    textAlign: "right",
                                  }}
                                >
                                  {pct.toFixed(1)}%
                                </span>
                              </div>
                            </td>
                          </>
                        ) : (
                          <>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text-2)",
                                fontSize: 12,
                              }}
                            >
                              {formatQty(row.quantity || 0)}
                            </td>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text-3)",
                                fontSize: 12,
                              }}
                            >
                              {formatRp(row.avg_price || 0)}
                            </td>
                            <td
                              style={{
                                padding: "9px 12px",
                                textAlign: "right",
                                ...mono,
                                color: "var(--text)",
                                fontSize: 12,
                                fontWeight: 600,
                              }}
                            >
                              {formatRp(row.amount)}
                            </td>
                            <td style={{ padding: "9px 12px" }}>
                              <div
                                style={{
                                  display: "flex",
                                  alignItems: "center",
                                  gap: 6,
                                }}
                              >
                                <div
                                  style={{
                                    flex: 1,
                                    height: 4,
                                    background: "var(--surface-3)",
                                    borderRadius: 2,
                                    overflow: "hidden",
                                  }}
                                >
                                  <div
                                    style={{
                                      width: `${Math.min(pct, 100)}%`,
                                      height: "100%",
                                      background:
                                        reportType === "brand"
                                          ? brandColor
                                          : "var(--accent)",
                                      borderRadius: 2,
                                      transition: "width 0.3s ease",
                                    }}
                                  />
                                </div>
                                <span
                                  style={{
                                    ...mono,
                                    fontSize: 10,
                                    color: "var(--text-4)",
                                    minWidth: 32,
                                    textAlign: "right",
                                  }}
                                >
                                  {pct.toFixed(1)}%
                                </span>
                              </div>
                            </td>
                          </>
                        )}
                      </tr>
                    </React.Fragment>
                  );
                })}
            </tbody>
            {!loading && filtered.length > 0 && (
              <tfoot
                style={{
                  borderTop: "1px solid var(--border)",
                  background: "var(--surface-2)",
                }}
              >
                <tr>
                  {reportType === "salesperson" ? (
                    <>
                      <td
                        colSpan={2}
                        style={{
                          padding: "8px 12px",
                          ...mono,
                          color: "var(--text-3)",
                          fontSize: 11,
                          fontWeight: 600,
                        }}
                      >
                        Total Value
                      </td>
                      <td
                        style={{
                          padding: "8px 12px",
                          textAlign: "right",
                          ...mono,
                          color: "var(--text)",
                          fontWeight: 700,
                        }}
                      >
                        {formatRp(filtered.reduce((s, r) => s + r.amount, 0))}
                      </td>
                      <td
                        style={{
                          padding: "8px 12px",
                          textAlign: "right",
                          ...mono,
                          color: "var(--text-3)",
                          fontWeight: 700,
                        }}
                      >
                        {filtered.reduce((s, r) => s + (r.invoice_count || 0), 0)}
                      </td>
                      <td />
                      <td />
                    </>
                  ) : (
                    <>
                      <td
                        colSpan={reportType === "item" ? 3 : 2}
                        style={{
                          padding: "8px 12px",
                          ...mono,
                          color: "var(--text-3)",
                          fontSize: 11,
                          fontWeight: 600,
                        }}
                      >
                        Total Value
                      </td>
                      <td
                        style={{
                          padding: "8px 12px",
                          textAlign: "right",
                          ...mono,
                          color: "var(--text-2)",
                          fontWeight: 700,
                        }}
                      >
                        {formatQty(
                          filtered.reduce((s, r) => s + (r.quantity || 0), 0),
                        )}
                      </td>
                      <td />
                      <td
                        style={{
                          padding: "8px 12px",
                          textAlign: "right",
                          ...mono,
                          color: "var(--text)",
                          fontWeight: 700,
                          fontSize: 13,
                        }}
                      >
                        {formatRp(filtered.reduce((s, r) => s + r.amount, 0))}
                      </td>
                      <td />
                    </>
                  )}
                </tr>
              </tfoot>
            )}
          </table>
        </div>

        {/* Note for salesperson */}
        {!loading && reportType === "salesperson" && (
          <p className="text-[var(--text-4)] text-xs mt-3">
            Sales by Salesperson includes all invoices (paid and unpaid) with an assigned
            Salesperson. Revenue is the invoice line total before PPN. For commission
            calculations, see Reports → Commission.
          </p>
        )}
      </div>
    </div>
  );
}
